"""
╔══════════════════════════════════════════════════════════════════════════╗
║  PHASE 8 — FastAPI Inference Server                                      ║
║  Fake News & Source Credibility Detector                                 ║
╠══════════════════════════════════════════════════════════════════════════╣
║  Serves the full credibility pipeline via a REST API:                    ║
║   • POST /predict  → credibility score + CI + verdict + top tokens       ║
║   • GET  /speaker/{name} → speaker profile from Phase 6                  ║
║   • GET  /health   → model status and loaded dataset stats               ║
║   • GET  /         → interactive Swagger UI (auto-generated by FastAPI)  ║
║                                                                          ║
║  Two-model ensemble at inference time:                                   ║
║   1. TF-IDF + Ridge (Phase 4) — fast, always available                  ║
║   2. DeBERTa (Phase 5)        — used if weights are available            ║
║   Ensemble score = 0.3 × TF-IDF + 0.7 × DeBERTa (or TF-IDF alone)     ║
║                                                                          ║
║  MC Dropout on DeBERTa gives calibrated 90% confidence intervals:       ║
║   "score: 0.32 ± 0.08" is more useful than just "0.32"                  ║
╠══════════════════════════════════════════════════════════════════════════╣
║  Outputs:                                                                ║
║    Running server at http://localhost:8000                                ║
║    API docs at  http://localhost:8000/docs                               ║
╚══════════════════════════════════════════════════════════════════════════╝

Install:
    pip install fastapi uvicorn[standard] pydantic joblib

Run:
    python phase8_api.py
    python phase8_api.py --port 8080
    python phase8_api.py --reload     # hot-reload for development

Example requests:
    curl -X POST http://localhost:8000/predict \\
         -H "Content-Type: application/json" \\
         -d '{"text":"Vaccines cause autism","speaker":"","context":""}'

    curl http://localhost:8000/speaker/Donald%20Trump
    curl http://localhost:8000/health
"""

import argparse
import importlib.util
import json
import os
import sys
import warnings
from pathlib import Path
from typing import Optional

os.environ.setdefault("PYTORCH_ENABLE_MPS_FALLBACK", "1")
warnings.filterwarnings("ignore")

_HERE     = Path(__file__).resolve().parent
MODEL_DIR = _HERE / "models"
DATA_DIR  = _HERE / "data"

# ─────────────────────────────────────────────────────────────────────────────
# Lazy imports — only pulled in when the server starts
# ─────────────────────────────────────────────────────────────────────────────
try:
    from fastapi import FastAPI, HTTPException
    from fastapi.responses import HTMLResponse, JSONResponse
    from pydantic import BaseModel, Field
    import uvicorn
except ImportError:
    print("fastapi / uvicorn not installed.\n"
          "Run: pip install fastapi uvicorn[standard]")
    sys.exit(1)

try:
    import numpy as np
    import torch
    import joblib
    from transformers import AutoTokenizer
except ImportError as e:
    print(f"Missing dependency: {e}\n"
          "Run: pip install torch transformers joblib numpy")
    sys.exit(1)


# ─────────────────────────────────────────────────────────────────────────────
# 1.  MODEL LOADING
# ─────────────────────────────────────────────────────────────────────────────

def _load_phase5_module():
    spec = importlib.util.spec_from_file_location(
        "phase5", _HERE / "phase5_deberta.py")
    p5 = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(p5)
    return p5


class ModelStore:
    """Holds all loaded models. Populated at startup, reused per request."""

    def __init__(self):
        self.tfidf_bundle   = None   # {vectorizer, scaler, model, feature_cols}
        self.deberta_model  = None
        self.deberta_tok    = None
        self.deberta_device = None
        self.p5             = None
        self.speaker_profiles: dict = {}
        self.dataset_stats:  dict = {}
        self.ready          = False

    def load(self):
        print("  Loading models…")
        self._load_tfidf()
        self._load_deberta()
        self._load_speaker_profiles()
        self._load_stats()
        self.ready = True
        print("  ✓ All models loaded.")

    def _load_tfidf(self):
        p = MODEL_DIR / "baseline_tfidf.pkl"
        if not p.exists():
            print(f"  WARNING: {p} not found — TF-IDF model unavailable.")
            return
        self.tfidf_bundle = joblib.load(p)
        print(f"  TF-IDF baseline loaded.")

    def _load_deberta(self):
        tok_path = MODEL_DIR / "deberta_tokenizer"
        wt_path  = MODEL_DIR / "deberta_best.pt"
        if not tok_path.exists() or not wt_path.exists():
            print("  WARNING: DeBERTa weights not found — using TF-IDF only.")
            return
        try:
            self.p5 = _load_phase5_module()
            device  = self.p5.detect_device()
            tok = AutoTokenizer.from_pretrained(str(tok_path), use_fast=False)
            model = self.p5.DeBERTaCredibilityModel().to(device)
            model.load_state_dict(
                torch.load(str(wt_path), map_location=device))
            model.eval()
            self.deberta_model  = model
            self.deberta_tok    = tok
            self.deberta_device = device
            print(f"  DeBERTa loaded on {device}.")
        except Exception as e:
            print(f"  WARNING: DeBERTa load failed ({e}) — using TF-IDF only.")

    def _load_speaker_profiles(self):
        p = MODEL_DIR / "speaker_profiles.json"
        if not p.exists():
            return
        data = json.loads(p.read_text())
        self.speaker_profiles = {
            r["speaker"].lower(): r for r in data.get("profiles", [])
        }
        print(f"  Speaker profiles: {len(self.speaker_profiles):,} loaded.")

    def _load_stats(self):
        p = DATA_DIR / "dataset_stats.json"
        if p.exists():
            self.dataset_stats = json.loads(p.read_text())


store = ModelStore()


# ─────────────────────────────────────────────────────────────────────────────
# 2.  INFERENCE HELPERS
# ─────────────────────────────────────────────────────────────────────────────

FEAT_COLS = [
    "vader_compound", "vader_pos", "vader_neg", "vader_neu",
    "pos_word_count", "neg_word_count", "pos_neg_ratio", "sentiment_extremity",
    "context_sentiment_risk", "context_adjusted_sentiment",
    "persuasive_context_flag", "context_credibility_prior", "token_length_approx",
]

def _compute_features(text: str, context: str,
                      context_prior: float = 0.5) -> list[float]:
    """
    Compute the 13 engineered features for a single claim at inference time.

    Delegates to the canonical Phase 2 extract_all_features() so the numbers
    match training EXACTLY. A previous local reimplementation drifted — it used
    fractional opinion-word counts, an unbounded pos/neg ratio, and abs(compound)
    for extremity — none of which matched the values the TF-IDF scaler and the
    DeBERTa fusion head were fitted on, quietly degrading every prediction.
    """
    try:
        from credibility_detector_phases123 import (
            extract_all_features, normalise_context)
        ctx   = normalise_context(context)
        feats = extract_all_features(text, ctx)          # 11 sentiment/interaction feats
        feats["context_credibility_prior"] = float(context_prior)
        feats["token_length_approx"]       = len(str(text)) / 4.0
        return [float(feats.get(c, 0.0)) for c in FEAT_COLS]
    except Exception:
        # Keep the vector shape correct even if imports/NLTK data are missing.
        return [0.0] * len(FEAT_COLS)


def predict_tfidf(text: str, features: list[float]) -> Optional[float]:
    if store.tfidf_bundle is None:
        return None
    from scipy.sparse import hstack, csr_matrix
    b = store.tfidf_bundle
    X_text = b["vectorizer"].transform([text])
    feat_arr = np.array(features).reshape(1, -1)
    X_feat = csr_matrix(b["scaler"].transform(feat_arr))
    X = hstack([X_text, X_feat])
    score = float(np.clip(b["model"].predict(X)[0], 0.0, 1.0))
    return score


def predict_deberta(text: str, speaker: str, context: str,
                    prior: float, features: list[float],
                    n_passes: int = 20) -> Optional[dict]:
    if store.deberta_model is None or store.p5 is None:
        return None
    result = store.p5.predict_with_uncertainty(
        model=store.deberta_model,
        tokenizer=store.deberta_tok,
        text=text,
        speaker=speaker,
        context=context,
        prior=prior,
        features=features,
        n_passes=n_passes,
        device=store.deberta_device,
    )
    return result


def ensemble_score(tfidf: Optional[float],
                   deberta: Optional[dict]) -> dict:
    """
    Weighted ensemble: 0.3 × TF-IDF + 0.7 × DeBERTa.
    Falls back to whichever model is available.
    """
    if deberta is not None and tfidf is not None:
        score = 0.3 * tfidf + 0.7 * deberta["mean"]
        lower = 0.3 * tfidf + 0.7 * deberta["lower"]
        upper = 0.3 * tfidf + 0.7 * deberta["upper"]
        model_used = "ensemble (DeBERTa×0.7 + TF-IDF×0.3)"
    elif deberta is not None:
        score = deberta["mean"]
        lower = deberta["lower"]
        upper = deberta["upper"]
        model_used = "deberta"
    elif tfidf is not None:
        score = tfidf
        lower = max(0.0, tfidf - 0.12)
        upper = min(1.0, tfidf + 0.12)
        model_used = "tfidf_baseline"
    else:
        raise HTTPException(503, "No models loaded. Run Phase 4 and/or Phase 5 first.")

    score = float(np.clip(score, 0.0, 1.0))
    verdict = ("FALSE" if score < 0.35 else
               "MIXED / UNVERIFIED" if score < 0.65 else "TRUE")
    return {
        "score":        round(score, 4),
        "lower_90ci":   round(float(np.clip(lower, 0.0, 1.0)), 4),
        "upper_90ci":   round(float(np.clip(upper, 0.0, 1.0)), 4),
        "verdict":      verdict,
        "model_used":   model_used,
    }


# ─────────────────────────────────────────────────────────────────────────────
# 3.  FASTAPI APP
# ─────────────────────────────────────────────────────────────────────────────

app = FastAPI(
    title="Fake News & Source Credibility Detector",
    description=(
        "Credibility score in [0, 1]: "
        "0 = false / fabricated, 1 = verified / true.\n\n"
        "Uses TF-IDF baseline (Phase 4) and DeBERTa-v3 (Phase 5) ensemble "
        "with MC Dropout confidence intervals."
    ),
    version="1.0.0",
)


@app.on_event("startup")
async def startup():
    store.load()


# ── Request / Response schemas ────────────────────────────────────────────────

class PredictRequest(BaseModel):
    text:    str   = Field(...,  example="Obama tripled the national debt.",
                           description="The claim or statement to evaluate.")
    speaker: str   = Field("",  example="Donald Trump",
                           description="Who made the claim (optional).")
    context: str   = Field("",  example="a campaign rally",
                           description="Where the claim was made (optional).")
    context_prior: Optional[float] = Field(
        None, ge=0.0, le=1.0,
        description="Override data-driven context prior [0–1]. "
                    "Auto-looked up from speaker profile if omitted.")
    mc_passes: int = Field(20, ge=1, le=100,
                           description="MC Dropout forward passes for CI.")


class PredictResponse(BaseModel):
    score:       float
    lower_90ci:  float
    upper_90ci:  float
    verdict:     str
    model_used:  str
    speaker_profile: Optional[dict] = None
    context_prior_used: float


# ── Endpoints ─────────────────────────────────────────────────────────────────

@app.get("/", response_class=HTMLResponse, include_in_schema=False)
async def root():
    return """<html><body>
    <h2>Fake News &amp; Source Credibility Detector — API</h2>
    <p><a href="/docs">Interactive Swagger UI</a></p>
    <p><a href="/redoc">ReDoc documentation</a></p>
    <p><a href="/health">Health check</a></p>
    </body></html>"""


@app.get("/health")
async def health():
    return {
        "status": "ready" if store.ready else "loading",
        "models": {
            "tfidf":   store.tfidf_bundle is not None,
            "deberta": store.deberta_model is not None,
        },
        "speaker_profiles": len(store.speaker_profiles),
        "dataset_stats":    store.dataset_stats,
    }


@app.post("/predict", response_model=PredictResponse)
async def predict(req: PredictRequest):
    if not store.ready:
        raise HTTPException(503, "Server is still loading models.")

    text    = req.text.strip()
    speaker = req.speaker.strip()
    context = req.context.strip()

    # Resolve context prior
    prior = req.context_prior
    speaker_info = store.speaker_profiles.get(speaker.lower())
    if prior is None:
        if speaker_info:
            prior = speaker_info.get("bayes_score", 0.5)
        else:
            prior = 0.5

    features = _compute_features(text, context, prior)

    tfidf_s   = predict_tfidf(text, features)
    deberta_r = predict_deberta(text, speaker, context, prior,
                                features, n_passes=req.mc_passes)
    result    = ensemble_score(tfidf_s, deberta_r)

    return PredictResponse(
        **result,
        speaker_profile=speaker_info,
        context_prior_used=round(prior, 4),
    )


@app.get("/speaker/{speaker_name}")
async def get_speaker(speaker_name: str):
    key = speaker_name.lower()
    profile = store.speaker_profiles.get(key)
    if profile is None:
        raise HTTPException(
            404,
            f"No profile for '{speaker_name}'. "
            "Run Phase 6 to build speaker profiles.")
    return profile


@app.get("/speakers/top")
async def top_speakers(n: int = 20, min_claims: int = 3,
                       order: str = "asc"):
    profiles = [p for p in store.speaker_profiles.values()
                if p["n_claims"] >= min_claims]
    reverse  = (order == "desc")
    ranked   = sorted(profiles, key=lambda p: p["bayes_score"],
                      reverse=reverse)
    return {"order": order, "speakers": ranked[:n]}


@app.get("/speakers/search")
async def search_speakers(q: str):
    q_low = q.lower()
    matches = [p for k, p in store.speaker_profiles.items()
               if q_low in k]
    return {"query": q, "matches": matches[:20]}


# ─────────────────────────────────────────────────────────────────────────────
# 4.  ENTRYPOINT
# ─────────────────────────────────────────────────────────────────────────────

def main():
    ap = argparse.ArgumentParser(description="Phase 8 — Credibility API Server")
    ap.add_argument("--host",   default="0.0.0.0")
    ap.add_argument("--port",   default=8000, type=int)
    ap.add_argument("--reload", action="store_true",
                    help="Hot-reload on code changes (development)")
    args = ap.parse_args()

    print("=" * 60)
    print("  PHASE 8 — FastAPI Inference Server")
    print(f"  http://localhost:{args.port}        (app)")
    print(f"  http://localhost:{args.port}/docs   (Swagger UI)")
    print(f"  http://localhost:{args.port}/health (status)")
    print("=" * 60)

    uvicorn.run(
        "phase8_api:app",
        host=args.host,
        port=args.port,
        reload=args.reload,
        log_level="info",
    )


if __name__ == "__main__":
    main()
